# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	"C:\Program Files\CMake\bin\ctest.exe" --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named basic_test

# Build rule for target.
basic_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 basic_test
.PHONY : basic_test

# fast build rule for target.
basic_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/build
.PHONY : basic_test/fast

#=============================================================================
# Target rules for targets named testB

# Build rule for target.
testB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 testB
.PHONY : testB

# fast build rule for target.
testB/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/build
.PHONY : testB/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googlemock\CMakeFiles\gmock.dir\build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googlemock\CMakeFiles\gmock_main.dir\build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googletest\CMakeFiles\gtest.dir\build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps\googletest-build\googletest\CMakeFiles\gtest_main.dir\build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

_tests/_test_files/basic_test.obj: _tests/_test_files/basic_test.cpp.obj
.PHONY : _tests/_test_files/basic_test.obj

# target to build an object file
_tests/_test_files/basic_test.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.obj
.PHONY : _tests/_test_files/basic_test.cpp.obj

_tests/_test_files/basic_test.i: _tests/_test_files/basic_test.cpp.i
.PHONY : _tests/_test_files/basic_test.i

# target to preprocess a source file
_tests/_test_files/basic_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.i
.PHONY : _tests/_test_files/basic_test.cpp.i

_tests/_test_files/basic_test.s: _tests/_test_files/basic_test.cpp.s
.PHONY : _tests/_test_files/basic_test.s

# target to generate assembly for a file
_tests/_test_files/basic_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.s
.PHONY : _tests/_test_files/basic_test.cpp.s

_tests/_test_files/testB.obj: _tests/_test_files/testB.cpp.obj
.PHONY : _tests/_test_files/testB.obj

# target to build an object file
_tests/_test_files/testB.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/_tests/_test_files/testB.cpp.obj
.PHONY : _tests/_test_files/testB.cpp.obj

_tests/_test_files/testB.i: _tests/_test_files/testB.cpp.i
.PHONY : _tests/_test_files/testB.i

# target to preprocess a source file
_tests/_test_files/testB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/_tests/_test_files/testB.cpp.i
.PHONY : _tests/_test_files/testB.cpp.i

_tests/_test_files/testB.s: _tests/_test_files/testB.cpp.s
.PHONY : _tests/_test_files/testB.s

# target to generate assembly for a file
_tests/_test_files/testB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/_tests/_test_files/testB.cpp.s
.PHONY : _tests/_test_files/testB.cpp.s

includes/animate/animate.obj: includes/animate/animate.cpp.obj
.PHONY : includes/animate/animate.obj

# target to build an object file
includes/animate/animate.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/animate/animate.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/animate/animate.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/animate/animate.cpp.obj
.PHONY : includes/animate/animate.cpp.obj

includes/animate/animate.i: includes/animate/animate.cpp.i
.PHONY : includes/animate/animate.i

# target to preprocess a source file
includes/animate/animate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/animate/animate.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/animate/animate.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/animate/animate.cpp.i
.PHONY : includes/animate/animate.cpp.i

includes/animate/animate.s: includes/animate/animate.cpp.s
.PHONY : includes/animate/animate.s

# target to generate assembly for a file
includes/animate/animate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/animate/animate.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/animate/animate.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/animate/animate.cpp.s
.PHONY : includes/animate/animate.cpp.s

includes/animate/random.obj: includes/animate/random.cpp.obj
.PHONY : includes/animate/random.obj

# target to build an object file
includes/animate/random.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/animate/random.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/animate/random.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/animate/random.cpp.obj
.PHONY : includes/animate/random.cpp.obj

includes/animate/random.i: includes/animate/random.cpp.i
.PHONY : includes/animate/random.i

# target to preprocess a source file
includes/animate/random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/animate/random.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/animate/random.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/animate/random.cpp.i
.PHONY : includes/animate/random.cpp.i

includes/animate/random.s: includes/animate/random.cpp.s
.PHONY : includes/animate/random.s

# target to generate assembly for a file
includes/animate/random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/animate/random.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/animate/random.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/animate/random.cpp.s
.PHONY : includes/animate/random.cpp.s

includes/animate/sidebar.obj: includes/animate/sidebar.cpp.obj
.PHONY : includes/animate/sidebar.obj

# target to build an object file
includes/animate/sidebar.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/animate/sidebar.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/animate/sidebar.cpp.obj
.PHONY : includes/animate/sidebar.cpp.obj

includes/animate/sidebar.i: includes/animate/sidebar.cpp.i
.PHONY : includes/animate/sidebar.i

# target to preprocess a source file
includes/animate/sidebar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/animate/sidebar.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/animate/sidebar.cpp.i
.PHONY : includes/animate/sidebar.cpp.i

includes/animate/sidebar.s: includes/animate/sidebar.cpp.s
.PHONY : includes/animate/sidebar.s

# target to generate assembly for a file
includes/animate/sidebar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/animate/sidebar.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/animate/sidebar.cpp.s
.PHONY : includes/animate/sidebar.cpp.s

includes/animate/system.obj: includes/animate/system.cpp.obj
.PHONY : includes/animate/system.obj

# target to build an object file
includes/animate/system.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/animate/system.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/animate/system.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/animate/system.cpp.obj
.PHONY : includes/animate/system.cpp.obj

includes/animate/system.i: includes/animate/system.cpp.i
.PHONY : includes/animate/system.i

# target to preprocess a source file
includes/animate/system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/animate/system.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/animate/system.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/animate/system.cpp.i
.PHONY : includes/animate/system.cpp.i

includes/animate/system.s: includes/animate/system.cpp.s
.PHONY : includes/animate/system.s

# target to generate assembly for a file
includes/animate/system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/animate/system.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/animate/system.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/animate/system.cpp.s
.PHONY : includes/animate/system.cpp.s

includes/exceptions/dividebyzero.obj: includes/exceptions/dividebyzero.cpp.obj
.PHONY : includes/exceptions/dividebyzero.obj

# target to build an object file
includes/exceptions/dividebyzero.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/exceptions/dividebyzero.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/exceptions/dividebyzero.cpp.obj
.PHONY : includes/exceptions/dividebyzero.cpp.obj

includes/exceptions/dividebyzero.i: includes/exceptions/dividebyzero.cpp.i
.PHONY : includes/exceptions/dividebyzero.i

# target to preprocess a source file
includes/exceptions/dividebyzero.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/exceptions/dividebyzero.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/exceptions/dividebyzero.cpp.i
.PHONY : includes/exceptions/dividebyzero.cpp.i

includes/exceptions/dividebyzero.s: includes/exceptions/dividebyzero.cpp.s
.PHONY : includes/exceptions/dividebyzero.s

# target to generate assembly for a file
includes/exceptions/dividebyzero.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/exceptions/dividebyzero.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/exceptions/dividebyzero.cpp.s
.PHONY : includes/exceptions/dividebyzero.cpp.s

includes/exceptions/missingparan.obj: includes/exceptions/missingparan.cpp.obj
.PHONY : includes/exceptions/missingparan.obj

# target to build an object file
includes/exceptions/missingparan.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/exceptions/missingparan.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/exceptions/missingparan.cpp.obj
.PHONY : includes/exceptions/missingparan.cpp.obj

includes/exceptions/missingparan.i: includes/exceptions/missingparan.cpp.i
.PHONY : includes/exceptions/missingparan.i

# target to preprocess a source file
includes/exceptions/missingparan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/exceptions/missingparan.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/exceptions/missingparan.cpp.i
.PHONY : includes/exceptions/missingparan.cpp.i

includes/exceptions/missingparan.s: includes/exceptions/missingparan.cpp.s
.PHONY : includes/exceptions/missingparan.s

# target to generate assembly for a file
includes/exceptions/missingparan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/exceptions/missingparan.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/exceptions/missingparan.cpp.s
.PHONY : includes/exceptions/missingparan.cpp.s

includes/graph/graph.obj: includes/graph/graph.cpp.obj
.PHONY : includes/graph/graph.obj

# target to build an object file
includes/graph/graph.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/graph/graph.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/graph/graph.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/graph/graph.cpp.obj
.PHONY : includes/graph/graph.cpp.obj

includes/graph/graph.i: includes/graph/graph.cpp.i
.PHONY : includes/graph/graph.i

# target to preprocess a source file
includes/graph/graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/graph/graph.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/graph/graph.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/graph/graph.cpp.i
.PHONY : includes/graph/graph.cpp.i

includes/graph/graph.s: includes/graph/graph.cpp.s
.PHONY : includes/graph/graph.s

# target to generate assembly for a file
includes/graph/graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/graph/graph.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/graph/graph.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/graph/graph.cpp.s
.PHONY : includes/graph/graph.cpp.s

includes/graph_info/graph_info.obj: includes/graph_info/graph_info.cpp.obj
.PHONY : includes/graph_info/graph_info.obj

# target to build an object file
includes/graph_info/graph_info.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/graph_info/graph_info.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/graph_info/graph_info.cpp.obj
.PHONY : includes/graph_info/graph_info.cpp.obj

includes/graph_info/graph_info.i: includes/graph_info/graph_info.cpp.i
.PHONY : includes/graph_info/graph_info.i

# target to preprocess a source file
includes/graph_info/graph_info.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/graph_info/graph_info.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/graph_info/graph_info.cpp.i
.PHONY : includes/graph_info/graph_info.cpp.i

includes/graph_info/graph_info.s: includes/graph_info/graph_info.cpp.s
.PHONY : includes/graph_info/graph_info.s

# target to generate assembly for a file
includes/graph_info/graph_info.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/graph_info/graph_info.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/graph_info/graph_info.cpp.s
.PHONY : includes/graph_info/graph_info.cpp.s

includes/plot/plot.obj: includes/plot/plot.cpp.obj
.PHONY : includes/plot/plot.obj

# target to build an object file
includes/plot/plot.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/plot/plot.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/plot/plot.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/plot/plot.cpp.obj
.PHONY : includes/plot/plot.cpp.obj

includes/plot/plot.i: includes/plot/plot.cpp.i
.PHONY : includes/plot/plot.i

# target to preprocess a source file
includes/plot/plot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/plot/plot.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/plot/plot.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/plot/plot.cpp.i
.PHONY : includes/plot/plot.cpp.i

includes/plot/plot.s: includes/plot/plot.cpp.s
.PHONY : includes/plot/plot.s

# target to generate assembly for a file
includes/plot/plot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/plot/plot.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/plot/plot.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/plot/plot.cpp.s
.PHONY : includes/plot/plot.cpp.s

includes/rpn/rpn.obj: includes/rpn/rpn.cpp.obj
.PHONY : includes/rpn/rpn.obj

# target to build an object file
includes/rpn/rpn.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/rpn/rpn.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/rpn/rpn.cpp.obj
.PHONY : includes/rpn/rpn.cpp.obj

includes/rpn/rpn.i: includes/rpn/rpn.cpp.i
.PHONY : includes/rpn/rpn.i

# target to preprocess a source file
includes/rpn/rpn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/rpn/rpn.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/rpn/rpn.cpp.i
.PHONY : includes/rpn/rpn.cpp.i

includes/rpn/rpn.s: includes/rpn/rpn.cpp.s
.PHONY : includes/rpn/rpn.s

# target to generate assembly for a file
includes/rpn/rpn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/rpn/rpn.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/rpn/rpn.cpp.s
.PHONY : includes/rpn/rpn.cpp.s

includes/shunting_yard/shunting_yard.obj: includes/shunting_yard/shunting_yard.cpp.obj
.PHONY : includes/shunting_yard/shunting_yard.obj

# target to build an object file
includes/shunting_yard/shunting_yard.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/shunting_yard/shunting_yard.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/shunting_yard/shunting_yard.cpp.obj
.PHONY : includes/shunting_yard/shunting_yard.cpp.obj

includes/shunting_yard/shunting_yard.i: includes/shunting_yard/shunting_yard.cpp.i
.PHONY : includes/shunting_yard/shunting_yard.i

# target to preprocess a source file
includes/shunting_yard/shunting_yard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/shunting_yard/shunting_yard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/shunting_yard/shunting_yard.cpp.i
.PHONY : includes/shunting_yard/shunting_yard.cpp.i

includes/shunting_yard/shunting_yard.s: includes/shunting_yard/shunting_yard.cpp.s
.PHONY : includes/shunting_yard/shunting_yard.s

# target to generate assembly for a file
includes/shunting_yard/shunting_yard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/shunting_yard/shunting_yard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/shunting_yard/shunting_yard.cpp.s
.PHONY : includes/shunting_yard/shunting_yard.cpp.s

includes/token/alpha.obj: includes/token/alpha.cpp.obj
.PHONY : includes/token/alpha.obj

# target to build an object file
includes/token/alpha.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/alpha.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/alpha.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/alpha.cpp.obj
.PHONY : includes/token/alpha.cpp.obj

includes/token/alpha.i: includes/token/alpha.cpp.i
.PHONY : includes/token/alpha.i

# target to preprocess a source file
includes/token/alpha.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/alpha.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/alpha.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/alpha.cpp.i
.PHONY : includes/token/alpha.cpp.i

includes/token/alpha.s: includes/token/alpha.cpp.s
.PHONY : includes/token/alpha.s

# target to generate assembly for a file
includes/token/alpha.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/alpha.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/alpha.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/alpha.cpp.s
.PHONY : includes/token/alpha.cpp.s

includes/token/function.obj: includes/token/function.cpp.obj
.PHONY : includes/token/function.obj

# target to build an object file
includes/token/function.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/function.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/function.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/function.cpp.obj
.PHONY : includes/token/function.cpp.obj

includes/token/function.i: includes/token/function.cpp.i
.PHONY : includes/token/function.i

# target to preprocess a source file
includes/token/function.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/function.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/function.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/function.cpp.i
.PHONY : includes/token/function.cpp.i

includes/token/function.s: includes/token/function.cpp.s
.PHONY : includes/token/function.s

# target to generate assembly for a file
includes/token/function.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/function.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/function.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/function.cpp.s
.PHONY : includes/token/function.cpp.s

includes/token/integer.obj: includes/token/integer.cpp.obj
.PHONY : includes/token/integer.obj

# target to build an object file
includes/token/integer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/integer.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/integer.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/integer.cpp.obj
.PHONY : includes/token/integer.cpp.obj

includes/token/integer.i: includes/token/integer.cpp.i
.PHONY : includes/token/integer.i

# target to preprocess a source file
includes/token/integer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/integer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/integer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/integer.cpp.i
.PHONY : includes/token/integer.cpp.i

includes/token/integer.s: includes/token/integer.cpp.s
.PHONY : includes/token/integer.s

# target to generate assembly for a file
includes/token/integer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/integer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/integer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/integer.cpp.s
.PHONY : includes/token/integer.cpp.s

includes/token/leftparen.obj: includes/token/leftparen.cpp.obj
.PHONY : includes/token/leftparen.obj

# target to build an object file
includes/token/leftparen.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/leftparen.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/leftparen.cpp.obj
.PHONY : includes/token/leftparen.cpp.obj

includes/token/leftparen.i: includes/token/leftparen.cpp.i
.PHONY : includes/token/leftparen.i

# target to preprocess a source file
includes/token/leftparen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/leftparen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/leftparen.cpp.i
.PHONY : includes/token/leftparen.cpp.i

includes/token/leftparen.s: includes/token/leftparen.cpp.s
.PHONY : includes/token/leftparen.s

# target to generate assembly for a file
includes/token/leftparen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/leftparen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/leftparen.cpp.s
.PHONY : includes/token/leftparen.cpp.s

includes/token/operator.obj: includes/token/operator.cpp.obj
.PHONY : includes/token/operator.obj

# target to build an object file
includes/token/operator.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/operator.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/operator.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/operator.cpp.obj
.PHONY : includes/token/operator.cpp.obj

includes/token/operator.i: includes/token/operator.cpp.i
.PHONY : includes/token/operator.i

# target to preprocess a source file
includes/token/operator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/operator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/operator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/operator.cpp.i
.PHONY : includes/token/operator.cpp.i

includes/token/operator.s: includes/token/operator.cpp.s
.PHONY : includes/token/operator.s

# target to generate assembly for a file
includes/token/operator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/operator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/operator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/operator.cpp.s
.PHONY : includes/token/operator.cpp.s

includes/token/rightparen.obj: includes/token/rightparen.cpp.obj
.PHONY : includes/token/rightparen.obj

# target to build an object file
includes/token/rightparen.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/rightparen.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/rightparen.cpp.obj
.PHONY : includes/token/rightparen.cpp.obj

includes/token/rightparen.i: includes/token/rightparen.cpp.i
.PHONY : includes/token/rightparen.i

# target to preprocess a source file
includes/token/rightparen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/rightparen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/rightparen.cpp.i
.PHONY : includes/token/rightparen.cpp.i

includes/token/rightparen.s: includes/token/rightparen.cpp.s
.PHONY : includes/token/rightparen.s

# target to generate assembly for a file
includes/token/rightparen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/rightparen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/rightparen.cpp.s
.PHONY : includes/token/rightparen.cpp.s

includes/token/tk_string.obj: includes/token/tk_string.cpp.obj
.PHONY : includes/token/tk_string.obj

# target to build an object file
includes/token/tk_string.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/tk_string.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/tk_string.cpp.obj
.PHONY : includes/token/tk_string.cpp.obj

includes/token/tk_string.i: includes/token/tk_string.cpp.i
.PHONY : includes/token/tk_string.i

# target to preprocess a source file
includes/token/tk_string.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/tk_string.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/tk_string.cpp.i
.PHONY : includes/token/tk_string.cpp.i

includes/token/tk_string.s: includes/token/tk_string.cpp.s
.PHONY : includes/token/tk_string.s

# target to generate assembly for a file
includes/token/tk_string.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/tk_string.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/tk_string.cpp.s
.PHONY : includes/token/tk_string.cpp.s

includes/token/token.obj: includes/token/token.cpp.obj
.PHONY : includes/token/token.obj

# target to build an object file
includes/token/token.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/token.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/token.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/token.cpp.obj
.PHONY : includes/token/token.cpp.obj

includes/token/token.i: includes/token/token.cpp.i
.PHONY : includes/token/token.i

# target to preprocess a source file
includes/token/token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/token.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/token.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/token.cpp.i
.PHONY : includes/token/token.cpp.i

includes/token/token.s: includes/token/token.cpp.s
.PHONY : includes/token/token.s

# target to generate assembly for a file
includes/token/token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/token/token.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/token/token.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/token/token.cpp.s
.PHONY : includes/token/token.cpp.s

includes/tokenizer/tokenizer.obj: includes/tokenizer/tokenizer.cpp.obj
.PHONY : includes/tokenizer/tokenizer.obj

# target to build an object file
includes/tokenizer/tokenizer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/tokenizer/tokenizer.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/tokenizer/tokenizer.cpp.obj
.PHONY : includes/tokenizer/tokenizer.cpp.obj

includes/tokenizer/tokenizer.i: includes/tokenizer/tokenizer.cpp.i
.PHONY : includes/tokenizer/tokenizer.i

# target to preprocess a source file
includes/tokenizer/tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/tokenizer/tokenizer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/tokenizer/tokenizer.cpp.i
.PHONY : includes/tokenizer/tokenizer.cpp.i

includes/tokenizer/tokenizer.s: includes/tokenizer/tokenizer.cpp.s
.PHONY : includes/tokenizer/tokenizer.s

# target to generate assembly for a file
includes/tokenizer/tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/tokenizer/tokenizer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/tokenizer/tokenizer.cpp.s
.PHONY : includes/tokenizer/tokenizer.cpp.s

includes/translate/translate.obj: includes/translate/translate.cpp.obj
.PHONY : includes/translate/translate.obj

# target to build an object file
includes/translate/translate.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/translate/translate.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/translate/translate.cpp.obj
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/translate/translate.cpp.obj
.PHONY : includes/translate/translate.cpp.obj

includes/translate/translate.i: includes/translate/translate.cpp.i
.PHONY : includes/translate/translate.i

# target to preprocess a source file
includes/translate/translate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/translate/translate.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/translate/translate.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/translate/translate.cpp.i
.PHONY : includes/translate/translate.cpp.i

includes/translate/translate.s: includes/translate/translate.cpp.s
.PHONY : includes/translate/translate.s

# target to generate assembly for a file
includes/translate/translate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/includes/translate/translate.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\basic_test.dir\build.make CMakeFiles/basic_test.dir/includes/translate/translate.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\testB.dir\build.make CMakeFiles/testB.dir/includes/translate/translate.cpp.s
.PHONY : includes/translate/translate.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... test
	@echo ... basic_test
	@echo ... gmock
	@echo ... gmock_main
	@echo ... gtest
	@echo ... gtest_main
	@echo ... main
	@echo ... testB
	@echo ... _tests/_test_files/basic_test.obj
	@echo ... _tests/_test_files/basic_test.i
	@echo ... _tests/_test_files/basic_test.s
	@echo ... _tests/_test_files/testB.obj
	@echo ... _tests/_test_files/testB.i
	@echo ... _tests/_test_files/testB.s
	@echo ... includes/animate/animate.obj
	@echo ... includes/animate/animate.i
	@echo ... includes/animate/animate.s
	@echo ... includes/animate/random.obj
	@echo ... includes/animate/random.i
	@echo ... includes/animate/random.s
	@echo ... includes/animate/sidebar.obj
	@echo ... includes/animate/sidebar.i
	@echo ... includes/animate/sidebar.s
	@echo ... includes/animate/system.obj
	@echo ... includes/animate/system.i
	@echo ... includes/animate/system.s
	@echo ... includes/exceptions/dividebyzero.obj
	@echo ... includes/exceptions/dividebyzero.i
	@echo ... includes/exceptions/dividebyzero.s
	@echo ... includes/exceptions/missingparan.obj
	@echo ... includes/exceptions/missingparan.i
	@echo ... includes/exceptions/missingparan.s
	@echo ... includes/graph/graph.obj
	@echo ... includes/graph/graph.i
	@echo ... includes/graph/graph.s
	@echo ... includes/graph_info/graph_info.obj
	@echo ... includes/graph_info/graph_info.i
	@echo ... includes/graph_info/graph_info.s
	@echo ... includes/plot/plot.obj
	@echo ... includes/plot/plot.i
	@echo ... includes/plot/plot.s
	@echo ... includes/rpn/rpn.obj
	@echo ... includes/rpn/rpn.i
	@echo ... includes/rpn/rpn.s
	@echo ... includes/shunting_yard/shunting_yard.obj
	@echo ... includes/shunting_yard/shunting_yard.i
	@echo ... includes/shunting_yard/shunting_yard.s
	@echo ... includes/token/alpha.obj
	@echo ... includes/token/alpha.i
	@echo ... includes/token/alpha.s
	@echo ... includes/token/function.obj
	@echo ... includes/token/function.i
	@echo ... includes/token/function.s
	@echo ... includes/token/integer.obj
	@echo ... includes/token/integer.i
	@echo ... includes/token/integer.s
	@echo ... includes/token/leftparen.obj
	@echo ... includes/token/leftparen.i
	@echo ... includes/token/leftparen.s
	@echo ... includes/token/operator.obj
	@echo ... includes/token/operator.i
	@echo ... includes/token/operator.s
	@echo ... includes/token/rightparen.obj
	@echo ... includes/token/rightparen.i
	@echo ... includes/token/rightparen.s
	@echo ... includes/token/tk_string.obj
	@echo ... includes/token/tk_string.i
	@echo ... includes/token/tk_string.s
	@echo ... includes/token/token.obj
	@echo ... includes/token/token.i
	@echo ... includes/token/token.s
	@echo ... includes/tokenizer/tokenizer.obj
	@echo ... includes/tokenizer/tokenizer.i
	@echo ... includes/tokenizer/tokenizer.s
	@echo ... includes/translate/translate.obj
	@echo ... includes/translate/translate.i
	@echo ... includes/translate/translate.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

