# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.22

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build"

# Include any dependencies generated for this target.
include CMakeFiles/basic_test.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/basic_test.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/basic_test.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/basic_test.dir/flags.make

CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.obj: ../_tests/_test_files/basic_test.cpp
CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.obj -MF CMakeFiles\basic_test.dir\_tests\_test_files\basic_test.cpp.obj.d -o CMakeFiles\basic_test.dir\_tests\_test_files\basic_test.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\_tests\_test_files\basic_test.cpp"

CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\_tests\_test_files\basic_test.cpp" > CMakeFiles\basic_test.dir\_tests\_test_files\basic_test.cpp.i

CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\_tests\_test_files\basic_test.cpp" -o CMakeFiles\basic_test.dir\_tests\_test_files\basic_test.cpp.s

CMakeFiles/basic_test.dir/includes/animate/animate.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/animate/animate.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/animate/animate.cpp.obj: ../includes/animate/animate.cpp
CMakeFiles/basic_test.dir/includes/animate/animate.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/basic_test.dir/includes/animate/animate.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/animate/animate.cpp.obj -MF CMakeFiles\basic_test.dir\includes\animate\animate.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\animate\animate.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\animate\animate.cpp"

CMakeFiles/basic_test.dir/includes/animate/animate.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/animate/animate.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\animate\animate.cpp" > CMakeFiles\basic_test.dir\includes\animate\animate.cpp.i

CMakeFiles/basic_test.dir/includes/animate/animate.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/animate/animate.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\animate\animate.cpp" -o CMakeFiles\basic_test.dir\includes\animate\animate.cpp.s

CMakeFiles/basic_test.dir/includes/animate/random.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/animate/random.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/animate/random.cpp.obj: ../includes/animate/random.cpp
CMakeFiles/basic_test.dir/includes/animate/random.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/basic_test.dir/includes/animate/random.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/animate/random.cpp.obj -MF CMakeFiles\basic_test.dir\includes\animate\random.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\animate\random.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\animate\random.cpp"

CMakeFiles/basic_test.dir/includes/animate/random.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/animate/random.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\animate\random.cpp" > CMakeFiles\basic_test.dir\includes\animate\random.cpp.i

CMakeFiles/basic_test.dir/includes/animate/random.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/animate/random.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\animate\random.cpp" -o CMakeFiles\basic_test.dir\includes\animate\random.cpp.s

CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.obj: ../includes/animate/sidebar.cpp
CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.obj -MF CMakeFiles\basic_test.dir\includes\animate\sidebar.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\animate\sidebar.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\animate\sidebar.cpp"

CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\animate\sidebar.cpp" > CMakeFiles\basic_test.dir\includes\animate\sidebar.cpp.i

CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\animate\sidebar.cpp" -o CMakeFiles\basic_test.dir\includes\animate\sidebar.cpp.s

CMakeFiles/basic_test.dir/includes/animate/system.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/animate/system.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/animate/system.cpp.obj: ../includes/animate/system.cpp
CMakeFiles/basic_test.dir/includes/animate/system.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/basic_test.dir/includes/animate/system.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/animate/system.cpp.obj -MF CMakeFiles\basic_test.dir\includes\animate\system.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\animate\system.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\animate\system.cpp"

CMakeFiles/basic_test.dir/includes/animate/system.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/animate/system.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\animate\system.cpp" > CMakeFiles\basic_test.dir\includes\animate\system.cpp.i

CMakeFiles/basic_test.dir/includes/animate/system.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/animate/system.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\animate\system.cpp" -o CMakeFiles\basic_test.dir\includes\animate\system.cpp.s

CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.obj: ../includes/exceptions/dividebyzero.cpp
CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.obj -MF CMakeFiles\basic_test.dir\includes\exceptions\dividebyzero.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\exceptions\dividebyzero.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\exceptions\dividebyzero.cpp"

CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\exceptions\dividebyzero.cpp" > CMakeFiles\basic_test.dir\includes\exceptions\dividebyzero.cpp.i

CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\exceptions\dividebyzero.cpp" -o CMakeFiles\basic_test.dir\includes\exceptions\dividebyzero.cpp.s

CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.obj: ../includes/exceptions/missingparan.cpp
CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_7) "Building CXX object CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.obj -MF CMakeFiles\basic_test.dir\includes\exceptions\missingparan.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\exceptions\missingparan.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\exceptions\missingparan.cpp"

CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\exceptions\missingparan.cpp" > CMakeFiles\basic_test.dir\includes\exceptions\missingparan.cpp.i

CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\exceptions\missingparan.cpp" -o CMakeFiles\basic_test.dir\includes\exceptions\missingparan.cpp.s

CMakeFiles/basic_test.dir/includes/graph/graph.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/graph/graph.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/graph/graph.cpp.obj: ../includes/graph/graph.cpp
CMakeFiles/basic_test.dir/includes/graph/graph.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_8) "Building CXX object CMakeFiles/basic_test.dir/includes/graph/graph.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/graph/graph.cpp.obj -MF CMakeFiles\basic_test.dir\includes\graph\graph.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\graph\graph.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\graph\graph.cpp"

CMakeFiles/basic_test.dir/includes/graph/graph.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/graph/graph.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\graph\graph.cpp" > CMakeFiles\basic_test.dir\includes\graph\graph.cpp.i

CMakeFiles/basic_test.dir/includes/graph/graph.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/graph/graph.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\graph\graph.cpp" -o CMakeFiles\basic_test.dir\includes\graph\graph.cpp.s

CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.obj: ../includes/graph_info/graph_info.cpp
CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_9) "Building CXX object CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.obj -MF CMakeFiles\basic_test.dir\includes\graph_info\graph_info.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\graph_info\graph_info.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\graph_info\graph_info.cpp"

CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\graph_info\graph_info.cpp" > CMakeFiles\basic_test.dir\includes\graph_info\graph_info.cpp.i

CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\graph_info\graph_info.cpp" -o CMakeFiles\basic_test.dir\includes\graph_info\graph_info.cpp.s

CMakeFiles/basic_test.dir/includes/plot/plot.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/plot/plot.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/plot/plot.cpp.obj: ../includes/plot/plot.cpp
CMakeFiles/basic_test.dir/includes/plot/plot.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_10) "Building CXX object CMakeFiles/basic_test.dir/includes/plot/plot.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/plot/plot.cpp.obj -MF CMakeFiles\basic_test.dir\includes\plot\plot.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\plot\plot.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\plot\plot.cpp"

CMakeFiles/basic_test.dir/includes/plot/plot.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/plot/plot.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\plot\plot.cpp" > CMakeFiles\basic_test.dir\includes\plot\plot.cpp.i

CMakeFiles/basic_test.dir/includes/plot/plot.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/plot/plot.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\plot\plot.cpp" -o CMakeFiles\basic_test.dir\includes\plot\plot.cpp.s

CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.obj: ../includes/rpn/rpn.cpp
CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_11) "Building CXX object CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.obj -MF CMakeFiles\basic_test.dir\includes\rpn\rpn.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\rpn\rpn.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\rpn\rpn.cpp"

CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\rpn\rpn.cpp" > CMakeFiles\basic_test.dir\includes\rpn\rpn.cpp.i

CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\rpn\rpn.cpp" -o CMakeFiles\basic_test.dir\includes\rpn\rpn.cpp.s

CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.obj: ../includes/shunting_yard/shunting_yard.cpp
CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_12) "Building CXX object CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.obj -MF CMakeFiles\basic_test.dir\includes\shunting_yard\shunting_yard.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\shunting_yard\shunting_yard.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\shunting_yard\shunting_yard.cpp"

CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\shunting_yard\shunting_yard.cpp" > CMakeFiles\basic_test.dir\includes\shunting_yard\shunting_yard.cpp.i

CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\shunting_yard\shunting_yard.cpp" -o CMakeFiles\basic_test.dir\includes\shunting_yard\shunting_yard.cpp.s

CMakeFiles/basic_test.dir/includes/token/alpha.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/token/alpha.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/token/alpha.cpp.obj: ../includes/token/alpha.cpp
CMakeFiles/basic_test.dir/includes/token/alpha.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_13) "Building CXX object CMakeFiles/basic_test.dir/includes/token/alpha.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/token/alpha.cpp.obj -MF CMakeFiles\basic_test.dir\includes\token\alpha.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\token\alpha.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\alpha.cpp"

CMakeFiles/basic_test.dir/includes/token/alpha.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/token/alpha.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\alpha.cpp" > CMakeFiles\basic_test.dir\includes\token\alpha.cpp.i

CMakeFiles/basic_test.dir/includes/token/alpha.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/token/alpha.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\alpha.cpp" -o CMakeFiles\basic_test.dir\includes\token\alpha.cpp.s

CMakeFiles/basic_test.dir/includes/token/function.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/token/function.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/token/function.cpp.obj: ../includes/token/function.cpp
CMakeFiles/basic_test.dir/includes/token/function.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_14) "Building CXX object CMakeFiles/basic_test.dir/includes/token/function.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/token/function.cpp.obj -MF CMakeFiles\basic_test.dir\includes\token\function.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\token\function.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\function.cpp"

CMakeFiles/basic_test.dir/includes/token/function.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/token/function.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\function.cpp" > CMakeFiles\basic_test.dir\includes\token\function.cpp.i

CMakeFiles/basic_test.dir/includes/token/function.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/token/function.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\function.cpp" -o CMakeFiles\basic_test.dir\includes\token\function.cpp.s

CMakeFiles/basic_test.dir/includes/token/integer.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/token/integer.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/token/integer.cpp.obj: ../includes/token/integer.cpp
CMakeFiles/basic_test.dir/includes/token/integer.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_15) "Building CXX object CMakeFiles/basic_test.dir/includes/token/integer.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/token/integer.cpp.obj -MF CMakeFiles\basic_test.dir\includes\token\integer.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\token\integer.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\integer.cpp"

CMakeFiles/basic_test.dir/includes/token/integer.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/token/integer.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\integer.cpp" > CMakeFiles\basic_test.dir\includes\token\integer.cpp.i

CMakeFiles/basic_test.dir/includes/token/integer.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/token/integer.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\integer.cpp" -o CMakeFiles\basic_test.dir\includes\token\integer.cpp.s

CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.obj: ../includes/token/leftparen.cpp
CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_16) "Building CXX object CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.obj -MF CMakeFiles\basic_test.dir\includes\token\leftparen.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\token\leftparen.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\leftparen.cpp"

CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\leftparen.cpp" > CMakeFiles\basic_test.dir\includes\token\leftparen.cpp.i

CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\leftparen.cpp" -o CMakeFiles\basic_test.dir\includes\token\leftparen.cpp.s

CMakeFiles/basic_test.dir/includes/token/operator.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/token/operator.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/token/operator.cpp.obj: ../includes/token/operator.cpp
CMakeFiles/basic_test.dir/includes/token/operator.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_17) "Building CXX object CMakeFiles/basic_test.dir/includes/token/operator.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/token/operator.cpp.obj -MF CMakeFiles\basic_test.dir\includes\token\operator.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\token\operator.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\operator.cpp"

CMakeFiles/basic_test.dir/includes/token/operator.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/token/operator.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\operator.cpp" > CMakeFiles\basic_test.dir\includes\token\operator.cpp.i

CMakeFiles/basic_test.dir/includes/token/operator.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/token/operator.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\operator.cpp" -o CMakeFiles\basic_test.dir\includes\token\operator.cpp.s

CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.obj: ../includes/token/rightparen.cpp
CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_18) "Building CXX object CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.obj -MF CMakeFiles\basic_test.dir\includes\token\rightparen.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\token\rightparen.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\rightparen.cpp"

CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\rightparen.cpp" > CMakeFiles\basic_test.dir\includes\token\rightparen.cpp.i

CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\rightparen.cpp" -o CMakeFiles\basic_test.dir\includes\token\rightparen.cpp.s

CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.obj: ../includes/token/tk_string.cpp
CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_19) "Building CXX object CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.obj -MF CMakeFiles\basic_test.dir\includes\token\tk_string.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\token\tk_string.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\tk_string.cpp"

CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\tk_string.cpp" > CMakeFiles\basic_test.dir\includes\token\tk_string.cpp.i

CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\tk_string.cpp" -o CMakeFiles\basic_test.dir\includes\token\tk_string.cpp.s

CMakeFiles/basic_test.dir/includes/token/token.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/token/token.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/token/token.cpp.obj: ../includes/token/token.cpp
CMakeFiles/basic_test.dir/includes/token/token.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_20) "Building CXX object CMakeFiles/basic_test.dir/includes/token/token.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/token/token.cpp.obj -MF CMakeFiles\basic_test.dir\includes\token\token.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\token\token.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\token.cpp"

CMakeFiles/basic_test.dir/includes/token/token.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/token/token.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\token.cpp" > CMakeFiles\basic_test.dir\includes\token\token.cpp.i

CMakeFiles/basic_test.dir/includes/token/token.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/token/token.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\token\token.cpp" -o CMakeFiles\basic_test.dir\includes\token\token.cpp.s

CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.obj: ../includes/tokenizer/tokenizer.cpp
CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_21) "Building CXX object CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.obj -MF CMakeFiles\basic_test.dir\includes\tokenizer\tokenizer.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\tokenizer\tokenizer.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\tokenizer\tokenizer.cpp"

CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\tokenizer\tokenizer.cpp" > CMakeFiles\basic_test.dir\includes\tokenizer\tokenizer.cpp.i

CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\tokenizer\tokenizer.cpp" -o CMakeFiles\basic_test.dir\includes\tokenizer\tokenizer.cpp.s

CMakeFiles/basic_test.dir/includes/translate/translate.cpp.obj: CMakeFiles/basic_test.dir/flags.make
CMakeFiles/basic_test.dir/includes/translate/translate.cpp.obj: CMakeFiles/basic_test.dir/includes_CXX.rsp
CMakeFiles/basic_test.dir/includes/translate/translate.cpp.obj: ../includes/translate/translate.cpp
CMakeFiles/basic_test.dir/includes/translate/translate.cpp.obj: CMakeFiles/basic_test.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_22) "Building CXX object CMakeFiles/basic_test.dir/includes/translate/translate.cpp.obj"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/basic_test.dir/includes/translate/translate.cpp.obj -MF CMakeFiles\basic_test.dir\includes\translate\translate.cpp.obj.d -o CMakeFiles\basic_test.dir\includes\translate\translate.cpp.obj -c "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\translate\translate.cpp"

CMakeFiles/basic_test.dir/includes/translate/translate.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/basic_test.dir/includes/translate/translate.cpp.i"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\translate\translate.cpp" > CMakeFiles\basic_test.dir\includes\translate\translate.cpp.i

CMakeFiles/basic_test.dir/includes/translate/translate.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/basic_test.dir/includes/translate/translate.cpp.s"
	C:\MinGW\bin\mingw32-g++.exe $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\includes\translate\translate.cpp" -o CMakeFiles\basic_test.dir\includes\translate\translate.cpp.s

# Object files for target basic_test
basic_test_OBJECTS = \
"CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/animate/animate.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/animate/random.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/animate/system.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/graph/graph.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/plot/plot.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/token/alpha.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/token/function.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/token/integer.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/token/operator.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/token/token.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.obj" \
"CMakeFiles/basic_test.dir/includes/translate/translate.cpp.obj"

# External object files for target basic_test
basic_test_EXTERNAL_OBJECTS =

bin/basic_test.exe: CMakeFiles/basic_test.dir/_tests/_test_files/basic_test.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/animate/animate.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/animate/random.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/animate/sidebar.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/animate/system.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/exceptions/dividebyzero.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/exceptions/missingparan.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/graph/graph.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/graph_info/graph_info.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/plot/plot.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/rpn/rpn.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/shunting_yard/shunting_yard.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/token/alpha.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/token/function.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/token/integer.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/token/leftparen.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/token/operator.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/token/rightparen.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/token/tk_string.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/token/token.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/tokenizer/tokenizer.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/includes/translate/translate.cpp.obj
bin/basic_test.exe: CMakeFiles/basic_test.dir/build.make
bin/basic_test.exe: lib/libgtestd.a
bin/basic_test.exe: C:/MinGW/lib/libsfml-system.a
bin/basic_test.exe: C:/MinGW/lib/libsfml-window.a
bin/basic_test.exe: C:/MinGW/lib/libsfml-graphics.a
bin/basic_test.exe: C:/MinGW/lib/libsfml-network.a
bin/basic_test.exe: C:/MinGW/lib/libsfml-audio.a
bin/basic_test.exe: CMakeFiles/basic_test.dir/linklibs.rsp
bin/basic_test.exe: CMakeFiles/basic_test.dir/objects1.rsp
bin/basic_test.exe: CMakeFiles/basic_test.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir="C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles" --progress-num=$(CMAKE_PROGRESS_23) "Linking CXX executable bin\basic_test.exe"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles\basic_test.dir\link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/basic_test.dir/build: bin/basic_test.exe
.PHONY : CMakeFiles/basic_test.dir/build

CMakeFiles/basic_test.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles\basic_test.dir\cmake_clean.cmake
.PHONY : CMakeFiles/basic_test.dir/clean

CMakeFiles/basic_test.dir/depend:
	$(CMAKE_COMMAND) -E cmake_depends "MinGW Makefiles" "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend" "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend" "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build" "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build" "C:\Users\kylal\OneDrive\Documents\School\SPR22 CS003A\99_00_final_project-kyend\build\CMakeFiles\basic_test.dir\DependInfo.cmake" --color=$(COLOR)
.PHONY : CMakeFiles/basic_test.dir/depend

